version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "10:00"
    commit-message:
      prefix: "⚙ "

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "10:00"
    commit-message:
      prefix: "⚙ "

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "10:00"
    commit-message:
      prefix: "⚙ "

  - package-ecosystem: "composer"
    directory: "/vendor-bin/phan"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "10:00"
    commit-message:
      prefix: "⚙ "

  - package-ecosystem: "composer"
    directory: "/vendor-bin/phpstan"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "10:00"
    commit-message:
      prefix: "⚙ "

  - package-ecosystem: "composer"
    directory: "/vendor-bin/psalm"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "10:00"
    commit-message:
      prefix: "⚙ "
