repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: no-commit-to-branch
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: check-merge-conflict
#      - id: check-symlinks
#      - id: destroyed-symlinks
      - id: check-json
#      - id: check-toml
#      - id: check-xml
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.15.3
    hooks:
      - id: gitleaks
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.1-beta
    hooks:
      - id: hadolint
