# https://taskfile.dev

version: '3'

silent: true

includes:
  precommit:
    aliases:
      - pc
    taskfile: .taskfiles/PreCommit.yaml

  docker: .taskfiles/Docker.yaml

tasks:
  default:
    desc: List available tasks in this project
    cmds:
      - task -a

  analyze-samples:
    desc: Run all the PHP static analyzers and store checkstyle reports to build/analyzer-outputs/
    cmds:
      - task: docker:build
      - task: docker:run-ni
        ignore_error: true
        vars:
          CMD: "composer run phan-samples-strict -- --no-progress-bar -m checkstyle"
          OUT: "build/analyzer-outputs/phan-strict.xml"
      - task: docker:run-ni
        ignore_error: true
        vars:
          CMD: "composer run phan-samples-loose -- --no-progress-bar -m checkstyle"
          OUT: "build/analyzer-outputs/phan-loose.xml"

      - task: docker:run-ni
        ignore_error: true
        vars:
          CMD: "composer run phpstan-samples-strict -- --no-progress --error-format=checkstyle"
          OUT: "build/analyzer-outputs/phpstan-strict.xml"

      - task: docker:run-ni
        ignore_error: true
        vars:
          CMD: "composer run phpstan-samples-loose -- --no-progress --error-format=checkstyle"
          OUT: "build/analyzer-outputs/phpstan-loose.xml"

      - task: docker:run-ni
        ignore_error: true
        vars:
          CMD: "composer run psalm-samples-strict -- --no-progress --output-format=checkstyle"
          OUT: "build/analyzer-outputs/psalm-strict.xml"

      - task: docker:run-ni
        ignore_error: true
        vars:
          CMD: "composer run psalm-samples-loose -- --no-progress --output-format=checkstyle"
          OUT: "build/analyzer-outputs/psalm-loose.xml"

  serve:
    desc: Run eleventy built-in dev server
    cmds:
      - task: analyze-samples
      - npm run start
