name: Analyze samples

on:
  push:
    branches-ignore:
      - main

  workflow_call:
    inputs:
      upload-artifacts:
        type: boolean

jobs:
  analyze:
    runs-on: ubuntu-latest
    name: Analyze the samples
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: build image
        run: |
          docker build -t cjw6k/analyzer -f Dockerfile .

      - name: phan
        continue-on-error: true
        run: |
          docker run --rm cjw6k/analyzer \
            composer run phan-samples-strict \
            -- --no-progress-bar -m checkstyle > build/analyzer-outputs/phan.xml

      - name: phpstan
        continue-on-error: true
        run: |
          docker run --rm cjw6k/analyzer \
            composer run phpstan-samples-strict \
            -- --no-progress --error-format=checkstyle > build/analyzer-outputs/phpstan.xml

      - name: psalm
        continue-on-error: true
        run: |
          docker run --rm cjw6k/analyzer \
            composer run psalm-samples-strict \
            -- --no-progress --output-format=checkstyle > build/analyzer-outputs/psalm.xml

      - name: upload artifacts
        if: inputs.upload-artifacts
        uses: actions/upload-artifact@v3
        with:
          name: analyses
          path: build/analyzer-outputs/*.xml
