name: Analyze samples

on:
  push:
    branches-ignore:
      - main

  workflow_call:
    inputs:
      upload-artifacts:
        type: boolean

jobs:
  analyze:
    runs-on: ubuntu-latest
    name: Analyze the samples
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build image
        run: |
          docker build -t cjw6k/analyzer -f Dockerfile .

      - name: phan-strict
        continue-on-error: true
        run: |
          docker run --rm cjw6k/analyzer \
            composer run phan-samples-strict \
            -- --no-progress-bar -m checkstyle > build/analyzer-outputs/phan-strict.xml

      - name: phan-loose
        continue-on-error: true
        run: |
          docker run --rm cjw6k/analyzer \
            composer run phan-samples-loose \
            -- --no-progress-bar -m checkstyle > build/analyzer-outputs/phan-loose.xml

      - name: phpstan-strict
        continue-on-error: true
        run: |
          docker run --rm cjw6k/analyzer \
            composer run phpstan-samples-strict \
            -- --no-progress --error-format=checkstyle > build/analyzer-outputs/phpstan-strict.xml

      - name: phpstan-loose
        continue-on-error: true
        run: |
          docker run --rm cjw6k/analyzer \
            composer run phpstan-samples-loose \
            -- --no-progress --error-format=checkstyle > build/analyzer-outputs/phpstan-loose.xml

      - name: psalm-strict
        continue-on-error: true
        run: |
          docker run --rm cjw6k/analyzer \
            composer run psalm-samples-strict \
            -- --no-progress --output-format=checkstyle > build/analyzer-outputs/psalm-strict.xml

      - name: psalm-loose
        continue-on-error: true
        run: |
          docker run --rm cjw6k/analyzer \
            composer run psalm-samples-loose \
            -- --no-progress --output-format=checkstyle > build/analyzer-outputs/psalm-loose.xml

      - name: upload artifacts
        if: inputs.upload-artifacts
        uses: actions/upload-artifact@v3
        with:
          name: analyses
          path: build/analyzer-outputs/*.xml
