name: Main

on:
  push

jobs:
  analyze-samples:
    runs-on: ubuntu-latest
    name: Analyze the samples
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build image
        run: |
          docker build -t cjw6k/analyzer -f Dockerfile .
      - name: phan
        continue-on-error: true
        run: |
          docker run --rm cjw6k/analyzer \
            composer run phan-samples-strict \
            -- --no-progress-bar -m checkstyle > _out/phan.xml
      - name: phpstan
        continue-on-error: true
        run: |
          docker run --rm cjw6k/analyzer \
            composer run phpstan-samples-strict \
            -- --no-progress --error-format=checkstyle > _out/phpstan.xml
      - name: psalm
        continue-on-error: true
        run: |
          docker run --rm cjw6k/analyzer \
            composer run psalm-samples-strict \
            -- --no-progress -output-format=checkstyle > _out/psalm.xml
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: analyses
          path: _out/*.xml
